/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as NewRouteImport } from './routes/new'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as StyleGuideRouteImport } from './routes/style-guide'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories.$categoryId'
import { Route as TaskTaskIdRouteImport } from './routes/task.$taskId'
import { Route as ApiPublicHooksDailyRemindersRouteImport } from './routes/api/public/hooks/daily-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleGuideRoute = StyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => CategoriesRoute,
} as any)
const TaskTaskIdRoute = TaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyRemindersRoute =
  ApiPublicHooksDailyRemindersRouteImport.update({
    id: '/api/public/hooks/daily-reminders',
    path: '/api/public/hooks/daily-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/new': typeof NewRoute
  '/reminders': typeof RemindersRoute
  '/style-guide': typeof StyleGuideRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/api/public/hooks/daily-reminders': typeof ApiPublicHooksDailyRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/new': typeof NewRoute
  '/reminders': typeof RemindersRoute
  '/style-guide': typeof StyleGuideRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/api/public/hooks/daily-reminders': typeof ApiPublicHooksDailyRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/new': typeof NewRoute
  '/reminders': typeof RemindersRoute
  '/style-guide': typeof StyleGuideRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/task/$taskId': typeof TaskTaskIdRoute
  '/api/public/hooks/daily-reminders': typeof ApiPublicHooksDailyRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categories'
    | '/new'
    | '/reminders'
    | '/style-guide'
    | '/categories/$categoryId'
    | '/task/$taskId'
    | '/api/public/hooks/daily-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categories'
    | '/new'
    | '/reminders'
    | '/style-guide'
    | '/categories/$categoryId'
    | '/task/$taskId'
    | '/api/public/hooks/daily-reminders'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/categories'
    | '/new'
    | '/reminders'
    | '/style-guide'
    | '/categories/$categoryId'
    | '/task/$taskId'
    | '/api/public/hooks/daily-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  NewRoute: typeof NewRoute
  RemindersRoute: typeof RemindersRoute
  StyleGuideRoute: typeof StyleGuideRoute
  TaskTaskIdRoute: typeof TaskTaskIdRoute
  ApiPublicHooksDailyRemindersRoute: typeof ApiPublicHooksDailyRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style-guide': {
      id: '/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof StyleGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/task/$taskId': {
      id: '/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/task/$taskId'
      preLoaderRoute: typeof TaskTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-reminders': {
      id: '/api/public/hooks/daily-reminders'
      path: '/api/public/hooks/daily-reminders'
      fullPath: '/api/public/hooks/daily-reminders'
      preLoaderRoute: typeof ApiPublicHooksDailyRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CategoriesRouteChildren {
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  NewRoute: NewRoute,
  RemindersRoute: RemindersRoute,
  StyleGuideRoute: StyleGuideRoute,
  TaskTaskIdRoute: TaskTaskIdRoute,
  ApiPublicHooksDailyRemindersRoute: ApiPublicHooksDailyRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
